from typing import Dict, Any, List, Optional
from app.llm import llm_client, extract_reply, require_real_completion
from app.policy import PolicyEvaluator
from app.database import db
from app.utils.logger import app_logger, audit_logger

class CybersecurityBrainTool:
    CYBER_LANGUAGES = {
        "python_security": "Python (Scapy, Impacket, pwntools, requests, socket, Cryptography)",
        "shell_bash": "Bash / Shell scripting (Nmap, Netcat, tshark, Gobuster, SQLmap)",
        "powershell_security": "PowerShell Security (Active Directory auditing, Event Log analysis, Empire)",
        "c_cpp_assembly": "C / C++ / x86_64 Assembly (Reverse Engineering, Buffer Overflow, Payload Analysis, GDB)",
        "go_rust_sec": "Go & Rust (Fast multithreaded scanners, memory-safe tooling, network analysis)",
        "web_security": "SQLi Payloads, XSS Payloads, PHP, JavaScript DOM Security, CSRF Tokens",
        "detection_rules": "YARA Rules (malware detection), Sigma Rules (SIEM detection), Snort / Suricata IDS Rules",
        "ruby_perl": "Ruby (Metasploit Framework Modules) & Perl"
    }

    @classmethod
    def parse_natural_security_intent(cls, natural_prompt: str, target_scope: Optional[str] = "127.0.0.1") -> Dict[str, Any]:
        """
        Parses natural language requests into structured cybersecurity workflows, 
        mapping user instructions to exact security languages, commands, or detection rules.
        """
        natural_prompt = natural_prompt.strip()
        app_logger.info(f"Parsing natural language security intent: '{natural_prompt}'")

        system_prompt = (
            "You are an expert Cybersecurity Engineer and Natural Language Security Analyst. "
            "Translate the user's natural language request into a precise, scope-checked "
            "cybersecurity plan, specifying the appropriate language/tool (Python, YARA, Sigma, Nmap, PowerShell) "
            "and step-by-step technical execution commands."
        )

        user_prompt = f"""
User Request: "{natural_prompt}"
Target Scope: {target_scope}

Analyze the request and provide:
1. **Natural Language Understanding (NLU) Summary**: What is the user trying to accomplish?
2. **Primary Security Language / Tool Required**: (e.g. Python Scapy, YARA Rule, Nmap Bash, Sigma Rule, PowerShell).
3. **Step-by-Step Technical Plan**: Safe, scope-checked commands or script outline.
4. **Safety & Policy Level**: Indicate if this requires Level 0/1/2 (read/scan) or Level 3 (explicit user approval).
"""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]

        try:
            llm_res = llm_client.generate_chat_completion(
                messages=messages,
                complexity="main",
                max_tokens=850
            )

            plan_text = require_real_completion(llm_res)

            audit_logger.info(f"Parsed natural language security intent for '{natural_prompt[:50]}'")

            return {
                "success": True,
                "natural_prompt": natural_prompt,
                "target_scope": target_scope,
                "security_plan": plan_text,
                "supported_languages": list(cls.CYBER_LANGUAGES.keys())
            }
        except Exception as e:
            app_logger.error(f"Error parsing security intent: {e}")
            return {"success": False, "error": f"Security NLU error: {str(e)}"}

    @classmethod
    def generate_yara_rule(cls, rule_name: str, strings_list: List[str], meta_description: str = "") -> Dict[str, Any]:
        """
        Generates a valid YARA rule syntax for malware & threat detection.
        """
        rule_name_clean = "".join(c for c in rule_name if c.isalnum() or c == "_") or "Custom_Rule"
        formatted_strings = "\n        ".join([f'$str{i+1} = "{s}"' for i, s in enumerate(strings_list)])

        yara_code = f"""rule {rule_name_clean} {{
    meta:
        description = "{meta_description or 'Generated by Local Personal Assistant'}"
        author = "Local Personal Assistant"
    strings:
        {formatted_strings}
    condition:
        any of them
}}"""

        # Save to SQLite Memory
        db.create_memory({
            "content": f"🛡️ [YARA RULE :: {rule_name_clean}]\n```yara\n{yara_code}\n```",
            "category": "yara_rule",
            "source": "cybersecurity_brain",
            "confidence": 1.0
        })

        return {
            "success": True,
            "rule_name": rule_name_clean,
            "yara_code": yara_code
        }

    @classmethod
    def generate_sigma_rule(cls, title: str, logsource_category: str, detection_selection: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generates a valid Sigma rule in YAML format for SIEM event log detection.
        """
        title_clean = title.strip()
        import yaml
        sigma_dict = {
            "title": title_clean,
            "status": "experimental",
            "description": f"Detects {title_clean}",
            "logsource": {
                "category": logsource_category,
                "product": "windows"
            },
            "detection": {
                "selection": detection_selection,
                "condition": "selection"
            },
            "level": "medium"
        }

        sigma_yaml = yaml.dump(sigma_dict, sort_keys=False)

        db.create_memory({
            "content": f"🛡️ [SIGMA SIEM RULE :: {title_clean}]\n```yaml\n{sigma_yaml}\n```",
            "category": "sigma_rule",
            "source": "cybersecurity_brain",
            "confidence": 1.0
        })

        return {
            "success": True,
            "title": title_clean,
            "sigma_yaml": sigma_yaml
        }
