"""WorldFirstReasoning — Phase 2 (Beanie AGI roadmap): world-first thinking.

Replaces the tool-first order (request → find tool → execute) with the
roadmap's order::

    request → understand goal → understand current world → retrieve relevant
    memories → (the cycle then forms hypotheses, chooses strategy, and only
    THEN identifies the capabilities required)

This module assembles the deterministic pre-cycle context — the *brief* —
from the Phase 3–5 organs:

- world:  matched entities + latest provenance-tracked states + visible gaps
- self:   knowledge state + matched capabilities (identified AFTER world)
- memory: meta-memory status + top evidence excerpts

Nothing here is generated by an LLM and nothing is invented: the brief is
pure retrieval output with provenance, bounded by a character budget, and it
is encoded into the brain's working-memory scratchpad — the channel the
cognitive cycle already reads when it assembles its prompt. If the gate
rejects the brief (attention decides it is not relevant), that decision is
recorded honestly. If assembly fails, the cycle runs exactly as before.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List

DEFAULT_CHAR_BUDGET = 900


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


class WorldFirstReasoning:
    """Assembles the world-first brief for a request."""

    def __init__(self, mind: Any) -> None:
        self.mind = mind

    # ── assembly ─────────────────────────────────────────────────────────
    def assemble_brief(self, user_text: str,
                       char_budget: int = DEFAULT_CHAR_BUDGET) -> Dict[str, Any]:
        """Deterministic, provenance-tagged, budget-bounded. Never raises into
        the caller's cognitive path (BeanieMind wraps this fail-open)."""
        text = str(user_text or "")

        # 1. WORLD — the environment before the toolset.
        world_ctx: Dict[str, Any] = {"matched": [], "gaps": []}
        try:
            u = self.mind.world.understand(text)
            if u.get("success") is not False:
                for m in u.get("matched_entities", []):
                    entity = m.get("entity", {})
                    states = m.get("latest_states", {})
                    world_ctx["matched"].append({
                        "name": entity.get("name"),
                        "type": entity.get("entity_type"),
                        "states": {
                            pred: {
                                "value": obs.get("value"),
                                "source": obs.get("source"),
                            } for pred, obs in (states or {}).items()
                        },
                    })
                world_ctx["gaps"] = list(u.get("gaps", []))[:6]
        except Exception:
            pass

        # 2. SELF — what she can do, asked AFTER the world is understood.
        self_ctx: Dict[str, Any] = {}
        try:
            assessment = self.mind.self_model.assess(text)
            self_ctx = {
                "knowledge": assessment.get("knowledge"),
                "confidence": assessment.get("confidence"),
                "possible_actions": assessment.get("possible_actions", []),
                "capabilities": [
                    c.get("action_type") for c in
                    (assessment.get("evidence", {}).get("capability_matches") or [])[:3]
                ],
            }
        except Exception:
            pass

        # 3. MEMORY — what she knows about what she knows + evidence.
        memory_ctx: Dict[str, Any] = {"status": "unknown", "evidence": []}
        try:
            meta = self.mind.memory.meta.ask(text)
            memory_ctx = {
                "status": meta.get("status"),
                "statement": meta.get("statement"),
                "evidence": [
                    {"kind": e.get("kind"), "content": e.get("content"),
                     "success": e.get("success")}
                    for e in (meta.get("evidence") or [])[:2]
                ],
            }
        except Exception:
            pass

        rendered = self.render(world_ctx, self_ctx, memory_ctx, char_budget)
        brief = {
            "text": text[:500],
            "assembled_at": _now_iso(),
            "world": world_ctx,
            "self": self_ctx,
            "memory": memory_ctx,
            "rendered": rendered,
            "chars": len(rendered),
            "has_positive_content": self._has_positive_content(world_ctx, self_ctx, memory_ctx),
        }
        return brief

    @staticmethod
    def _has_positive_content(world_ctx: Dict[str, Any], self_ctx: Dict[str, Any],
                              memory_ctx: Dict[str, Any]) -> bool:
        """A brief with nothing relevant adds noise, not intelligence. Only
        positive content earns a place in the prompt; pure ignorance stays on
        the /mind surfaces where the owner can inspect it."""
        if world_ctx.get("matched"):
            return True
        if self_ctx.get("knowledge") in ("known", "partial"):
            return True
        if memory_ctx.get("status") in ("remembered_done", "knows_how", "heard_about"):
            return True
        return False

    # ── rendering (order = the roadmap's order: world → self → memory) ──
    def render(self, world_ctx: Dict[str, Any], self_ctx: Dict[str, Any],
               memory_ctx: Dict[str, Any], char_budget: int) -> str:
        lines: List[str] = []

        if world_ctx.get("matched"):
            lines.append("[WORLD CONTEXT] (provenance-tracked)")
            for m in world_ctx["matched"][:5]:
                states = "; ".join(
                    f"{pred}={s.get('value')} [{s.get('source')}]"
                    for pred, s in (m.get("states") or {}).items()
                )
                suffix = f": {states}" if states else ""
                lines.append(f"- {m.get('name')} ({m.get('type')}){suffix}")
        if world_ctx.get("gaps"):
            lines.append(f"- not yet in world model: {', '.join(world_ctx['gaps'][:5])}")

        if self_ctx:
            caps = ", ".join(self_ctx.get("capabilities") or []) or "none matched"
            lines.append("[SELF STATE]")
            lines.append(
                f"- knowledge={self_ctx.get('knowledge')} "
                f"confidence={self_ctx.get('confidence')} "
                f"capabilities: {caps}"
            )

        if memory_ctx.get("status") and memory_ctx.get("status") != "unknown":
            lines.append("[WHAT I ALREADY KNOW]")
            lines.append(f"- {memory_ctx.get('statement')}")
            for e in memory_ctx.get("evidence", [])[:2]:
                lines.append(f"  ({e.get('kind')}) {e.get('content')}")

        rendered = "\n".join(lines)
        if len(rendered) > char_budget:
            rendered = rendered[:char_budget].rsplit("\n", 1)[0] + "\n[truncated]"
        return rendered

    # ── delivery into the brain's scratchpad ─────────────────────────────
    def deliver(self, user_text: str, brief: Dict[str, Any]) -> Dict[str, Any]:
        """Encode the brief into working memory — the channel the cognitive
        cycle already reads. The attention gate decides acceptance; the
        decision is returned, never overridden."""
        if not brief.get("has_positive_content") or not brief.get("rendered"):
            return {"delivered": False, "reason": "nothing relevant known — brief skipped"}
        working = getattr(self.mind.runtime, "working_memory", None)
        if working is None:
            return {"delivered": False, "reason": "working memory not wired"}
        try:
            decision = working.encode(
                brief["rendered"],
                kind="retrieved_memory",
                source="beanie_world_brief",
                salience=0.95,
                goal_text=user_text,
            )
        except Exception as exc:
            return {"delivered": False, "reason": f"{type(exc).__name__}: {exc}"}
        return {"delivered": bool(decision.get("accepted")), "gate": decision}
