"""
Everyday Life and Practical Knowledge

Facts about everyday life including:
- Food and cooking
- Household management
- Health and wellness
- Transportation
- Money and shopping
"""

EVERYDAY_KNOWLEDGE_FACTS = [
    # ── Food and Cooking ──
    {"fact_id": "daily_001", "category": "everyday", "fact": "Food spoils if left at room temperature too long", "confidence": 1.0},
    {"fact_id": "daily_002", "category": "everyday", "fact": "Refrigeration slows food spoilage", "confidence": 1.0},
    {"fact_id": "daily_003", "category": "everyday", "fact": "Cooking kills bacteria in food", "confidence": 1.0},
    {"fact_id": "daily_004", "category": "everyday", "fact": "Raw chicken can carry salmonella", "confidence": 1.0},
    {"fact_id": "daily_005", "category": "everyday", "fact": "Expired food may not be safe to eat", "confidence": 1.0},
    {"fact_id": "daily_006", "category": "everyday", "fact": "Salt enhances the flavor of food", "confidence": 1.0},
    {"fact_id": "daily_007", "category": "everyday", "fact": "Sugar makes food taste sweet", "confidence": 1.0},
    {"fact_id": "daily_008", "category": "everyday", "fact": "Boiling water is 100 degrees Celsius", "confidence": 1.0},
    {"fact_id": "daily_009", "category": "everyday", "fact": "Pasta is cooked in boiling water", "confidence": 1.0},
    {"fact_id": "daily_010", "category": "everyday", "fact": "Bread is made from flour", "confidence": 1.0},
    {"fact_id": "daily_011", "category": "everyday", "fact": "Baking uses an oven", "confidence": 1.0},
    {"fact_id": "daily_012", "category": "everyday", "fact": "Frying uses oil in a pan", "confidence": 1.0},
    {"fact_id": "daily_013", "category": "everyday", "fact": "Microwaves heat food quickly", "confidence": 1.0},
    {"fact_id": "daily_014", "category": "everyday", "fact": "Frozen food needs to be thawed before cooking", "confidence": 0.9},
    {"fact_id": "daily_015", "category": "everyday", "fact": "Coffee is made from roasted coffee beans", "confidence": 1.0},
    {"fact_id": "daily_016", "category": "everyday", "fact": "Tea is made from tea leaves steeped in hot water", "confidence": 1.0},
    {"fact_id": "daily_017", "category": "everyday", "fact": "Fruits and vegetables are healthy to eat", "confidence": 1.0},
    {"fact_id": "daily_018", "category": "everyday", "fact": "Dairy products come from milk", "confidence": 1.0},
    {"fact_id": "daily_019", "category": "everyday", "fact": "Leftover food should be refrigerated", "confidence": 1.0},
    {"fact_id": "daily_020", "category": "everyday", "fact": "Sharp knives are safer than dull knives", "confidence": 0.9},
    {"fact_id": "daily_021", "category": "everyday", "fact": "A recipe lists ingredients and cooking steps", "confidence": 1.0},
    {"fact_id": "daily_022", "category": "everyday", "fact": "Measuring cups are used for liquid ingredients", "confidence": 1.0},
    {"fact_id": "daily_023", "category": "everyday", "fact": "Yeast makes bread rise", "confidence": 1.0},
    {"fact_id": "daily_024", "category": "everyday", "fact": "Chocolate melts when heated", "confidence": 1.0},
    {"fact_id": "daily_025", "category": "everyday", "fact": "Oil and water do not mix", "confidence": 1.0},

    # ── Household Management ──
    {"fact_id": "daily_101", "category": "everyday", "fact": "Doing laundry cleans clothes", "confidence": 1.0},
    {"fact_id": "daily_102", "category": "everyday", "fact": "Detergent helps clean clothes", "confidence": 1.0},
    {"fact_id": "daily_103", "category": "everyday", "fact": "Hot water cleans better than cold water", "confidence": 0.9},
    {"fact_id": "daily_104", "category": "everyday", "fact": "White clothes should be washed separately from colored clothes", "confidence": 0.9},
    {"fact_id": "daily_105", "category": "everyday", "fact": "Vacuuming removes dust from carpets", "confidence": 1.0},
    {"fact_id": "daily_106", "category": "everyday", "fact": "Dusting keeps surfaces clean", "confidence": 1.0},
    {"fact_id": "daily_107", "category": "everyday", "fact": "Taking out the trash prevents odors", "confidence": 1.0},
    {"fact_id": "daily_108", "category": "everyday", "fact": "Dishes need to be washed after use", "confidence": 1.0},
    {"fact_id": "daily_109", "category": "everyday", "fact": "A dishwasher automates dish washing", "confidence": 1.0},
    {"fact_id": "daily_110", "category": "everyday", "fact": "Light bulbs need to be replaced when they burn out", "confidence": 1.0},
    {"fact_id": "daily_111", "category": "everyday", "fact": "Turning off lights saves electricity", "confidence": 1.0},
    {"fact_id": "daily_112", "category": "everyday", "fact": "Heating costs more when windows are open", "confidence": 1.0},
    {"fact_id": "daily_113", "category": "everyday", "fact": "Plants need water and sunlight to grow", "confidence": 1.0},
    {"fact_id": "daily_114", "category": "everyday", "fact": "Overwatering plants can kill them", "confidence": 1.0},
    {"fact_id": "daily_115", "category": "everyday", "fact": "Furniture needs to be assembled before use", "confidence": 1.0},
    {"fact_id": "daily_116", "category": "everyday", "fact": "A toolbox contains tools for repairs", "confidence": 1.0},
    {"fact_id": "daily_117", "category": "everyday", "fact": "Screws hold things together", "confidence": 1.0},
    {"fact_id": "daily_118", "category": "everyday", "fact": "Paint dries over time", "confidence": 1.0},
    {"fact_id": "daily_119", "category": "everyday", "fact": "Leaky faucets waste water", "confidence": 1.0},
    {"fact_id": "daily_120", "category": "everyday", "fact": "Cleaning supplies should be stored safely away from children", "confidence": 1.0},

    # ── Health and Wellness ──
    {"fact_id": "daily_201", "category": "everyday", "fact": "Drinking water is essential for health", "confidence": 1.0},
    {"fact_id": "daily_202", "category": "everyday", "fact": "Exercise improves physical health", "confidence": 1.0},
    {"fact_id": "daily_203", "category": "everyday", "fact": "Sleep is necessary for recovery", "confidence": 1.0},
    {"fact_id": "daily_204", "category": "everyday", "fact": "Smoking is harmful to health", "confidence": 1.0},
    {"fact_id": "daily_205", "category": "everyday", "fact": "Washing hands prevents illness", "confidence": 1.0},
    {"fact_id": "daily_206", "category": "everyday", "fact": "Fever is a sign of illness", "confidence": 1.0},
    {"fact_id": "daily_207", "category": "everyday", "fact": "Cuts should be cleaned and bandaged", "confidence": 1.0},
    {"fact_id": "daily_208", "category": "everyday", "fact": "Sunscreen protects skin from UV damage", "confidence": 1.0},
    {"fact_id": "daily_209", "category": "everyday", "fact": "Brushing teeth prevents cavities", "confidence": 1.0},
    {"fact_id": "daily_210", "category": "everyday", "fact": "Stress can cause health problems", "confidence": 1.0},
    {"fact_id": "daily_211", "category": "everyday", "fact": "Meditation can reduce stress", "confidence": 0.9},
    {"fact_id": "daily_212", "category": "everyday", "fact": "Vitamins support bodily functions", "confidence": 0.9},
    {"fact_id": "daily_213", "category": "everyday", "fact": "Dehydration causes headaches and fatigue", "confidence": 1.0},
    {"fact_id": "daily_214", "category": "everyday", "fact": "Too much sugar is unhealthy", "confidence": 1.0},
    {"fact_id": "daily_215", "category": "everyday", "fact": "Sitting for too long is unhealthy", "confidence": 1.0},
    {"fact_id": "daily_216", "category": "everyday", "fact": "Regular checkups help detect health issues early", "confidence": 1.0},
    {"fact_id": "daily_217", "category": "everyday", "fact": "Allergies cause reactions to certain substances", "confidence": 1.0},
    {"fact_id": "daily_218", "category": "everyday", "fact": "Sunburn happens from too much sun exposure", "confidence": 1.0},
    {"fact_id": "daily_219", "category": "everyday", "fact": "Caffeine can keep you awake", "confidence": 1.0},
    {"fact_id": "daily_220", "category": "everyday", "fact": "Alcohol impairs judgment and coordination", "confidence": 1.0},

    # ── Transportation ──
    {"fact_id": "daily_301", "category": "everyday", "fact": "Cars need fuel to run", "confidence": 1.0},
    {"fact_id": "daily_302", "category": "everyday", "fact": "Electric cars need to be charged", "confidence": 1.0},
    {"fact_id": "daily_303", "category": "everyday", "fact": "Tires need proper air pressure", "confidence": 1.0},
    {"fact_id": "daily_304", "category": "everyday", "fact": "Cars need regular oil changes", "confidence": 1.0},
    {"fact_id": "daily_305", "category": "everyday", "fact": "Traffic lights control intersection flow", "confidence": 1.0},
    {"fact_id": "daily_306", "category": "everyday", "fact": "Red means stop, green means go", "confidence": 1.0},
    {"fact_id": "daily_307", "category": "everyday", "fact": "Seatbelts save lives in accidents", "confidence": 1.0},
    {"fact_id": "daily_308", "category": "everyday", "fact": "Speed limits exist for safety", "confidence": 1.0},
    {"fact_id": "daily_309", "category": "everyday", "fact": "Driving while tired is dangerous", "confidence": 1.0},
    {"fact_id": "daily_310", "category": "everyday", "fact": "Bicycles are human-powered vehicles", "confidence": 1.0},
    {"fact_id": "daily_311", "category": "everyday", "fact": "Helmets protect the head while cycling", "confidence": 1.0},
    {"fact_id": "daily_312", "category": "everyday", "fact": "Buses follow fixed routes", "confidence": 1.0},
    {"fact_id": "daily_313", "category": "everyday", "fact": "Trains run on tracks", "confidence": 1.0},
    {"fact_id": "daily_314", "category": "everyday", "fact": "Airplanes fly through the air", "confidence": 1.0},
    {"fact_id": "daily_315", "category": "everyday", "fact": "Walking is the simplest form of transportation", "confidence": 1.0},
    {"fact_id": "daily_316", "category": "everyday", "fact": "GPS helps navigate to destinations", "confidence": 1.0},
    {"fact_id": "daily_317", "category": "everyday", "fact": "Rush hour has the most traffic", "confidence": 1.0},
    {"fact_id": "daily_318", "category": "everyday", "fact": "Parking tickets are issued for illegal parking", "confidence": 1.0},
    {"fact_id": "daily_319", "category": "everyday", "fact": "Car insurance is required by law", "confidence": 0.9},
    {"fact_id": "daily_320", "category": "everyday", "fact": "Driving in rain requires more caution", "confidence": 1.0},

    # ── Money and Shopping ──
    {"fact_id": "daily_401", "category": "everyday", "fact": "Things cost money to buy", "confidence": 1.0},
    {"fact_id": "daily_402", "category": "everyday", "fact": "Prices indicate how much things cost", "confidence": 1.0},
    {"fact_id": "daily_403", "category": "everyday", "fact": "Sales tax is added to purchase prices", "confidence": 1.0},
    {"fact_id": "daily_404", "category": "everyday", "fact": "Credit cards allow deferred payment", "confidence": 1.0},
    {"fact_id": "daily_405", "category": "everyday", "fact": "Debit cards use money from your bank account", "confidence": 1.0},
    {"fact_id": "daily_406", "category": "everyday", "fact": "Receipts prove purchase", "confidence": 1.0},
    {"fact_id": "daily_407", "category": "everyday", "fact": "Coupons reduce the price of items", "confidence": 1.0},
    {"fact_id": "daily_408", "category": "everyday", "fact": "Sales offer items at reduced prices", "confidence": 1.0},
    {"fact_id": "daily_409", "category": "everyday", "fact": "Budgeting helps manage money", "confidence": 1.0},
    {"fact_id": "daily_410", "category": "everyday", "fact": "Saving money builds wealth over time", "confidence": 1.0},
    {"fact_id": "daily_411", "category": "everyday", "fact": "Interest is earned on savings", "confidence": 1.0},
    {"fact_id": "daily_412", "category": "everyday", "fact": "Loans must be repaid with interest", "confidence": 1.0},
    {"fact_id": "daily_413", "category": "everyday", "fact": "Bills must be paid on time to avoid penalties", "confidence": 1.0},
    {"fact_id": "daily_414", "category": "everyday", "fact": "Online shopping delivers items to your door", "confidence": 1.0},
    {"fact_id": "daily_415", "category": "everyday", "fact": "Returns allow sending back unwanted items", "confidence": 1.0},
    {"fact_id": "daily_416", "category": "everyday", "fact": "Warranties cover product defects", "confidence": 1.0},
    {"fact_id": "daily_417", "category": "everyday", "fact": "Comparison shopping finds the best price", "confidence": 1.0},
    {"fact_id": "daily_418", "category": "everyday", "fact": "Groceries are everyday food purchases", "confidence": 1.0},
    {"fact_id": "daily_419", "category": "everyday", "fact": "Rent is paid monthly for housing", "confidence": 1.0},
    {"fact_id": "daily_420", "category": "everyday", "fact": "Taxes fund public services", "confidence": 1.0},
]
