"""
Physical World Knowledge

Facts about the physical world including:
- Gravity and physics
- Object permanence
- Material properties
- Physical laws
- Everyday physics
- Temperature and states of matter
- Light and optics
- Electricity and magnetism
"""

PHYSICAL_WORLD_FACTS = [
    # ── Gravity and Physics ──
    {"fact_id": "phys_001", "category": "physical", "fact": "Objects fall down due to gravity", "confidence": 1.0},
    {"fact_id": "phys_002", "category": "physical", "fact": "Heavier objects fall at the same rate as lighter objects in a vacuum", "confidence": 1.0},
    {"fact_id": "phys_003", "category": "physical", "fact": "Objects dropped from higher fall faster due to acceleration", "confidence": 1.0},
    {"fact_id": "phys_004", "category": "physical", "fact": "Objects in motion stay in motion unless acted upon by a force", "confidence": 1.0},
    {"fact_id": "phys_005", "category": "physical", "fact": "Objects at rest stay at rest unless acted upon by a force", "confidence": 1.0},
    {"fact_id": "phys_006", "category": "physical", "fact": "Friction slows down moving objects", "confidence": 1.0},
    {"fact_id": "phys_007", "category": "physical", "fact": "Smooth surfaces have less friction than rough surfaces", "confidence": 1.0},
    {"fact_id": "phys_008", "category": "physical", "fact": "Ice has less friction than dry surfaces", "confidence": 1.0},
    {"fact_id": "phys_009", "category": "physical", "fact": "Water has less friction than dry surfaces", "confidence": 1.0},
    {"fact_id": "phys_010", "category": "physical", "fact": "Objects float if they are less dense than water", "confidence": 1.0},
    {"fact_id": "phys_011", "category": "physical", "fact": "Objects sink if they are more dense than water", "confidence": 1.0},
    {"fact_id": "phys_012", "category": "physical", "fact": "Wood floats in water", "confidence": 1.0},
    {"fact_id": "phys_013", "category": "physical", "fact": "Metal sinks in water", "confidence": 1.0},
    {"fact_id": "phys_014", "category": "physical", "fact": "Ice floats in water", "confidence": 1.0},
    {"fact_id": "phys_015", "category": "physical", "fact": "Oil floats on water", "confidence": 1.0},
    {"fact_id": "phys_016", "category": "physical", "fact": "Hot air rises", "confidence": 1.0},
    {"fact_id": "phys_017", "category": "physical", "fact": "Cold air sinks", "confidence": 1.0},
    {"fact_id": "phys_018", "category": "physical", "fact": "Heat rises in convection currents", "confidence": 1.0},
    {"fact_id": "phys_019", "category": "physical", "fact": "Cold air is denser than hot air", "confidence": 1.0},
    {"fact_id": "phys_020", "category": "physical", "fact": "Pressure increases with depth in water", "confidence": 1.0},
    {"fact_id": "phys_021", "category": "physical", "fact": "Gravity pulls objects toward the center of the Earth", "confidence": 1.0},
    {"fact_id": "phys_022", "category": "physical", "fact": "The Moon has less gravity than Earth", "confidence": 1.0},
    {"fact_id": "phys_023", "category": "physical", "fact": "Objects weigh less on the Moon than on Earth", "confidence": 1.0},
    {"fact_id": "phys_024", "category": "physical", "fact": "Throwing a ball upward makes it slow down then fall back", "confidence": 1.0},
    {"fact_id": "phys_025", "category": "physical", "fact": "A rolling ball eventually stops due to friction", "confidence": 1.0},
    {"fact_id": "phys_026", "category": "physical", "fact": "Pendulums swing back and forth due to gravity", "confidence": 1.0},
    {"fact_id": "phys_027", "category": "physical", "fact": "Air resistance slows falling objects", "confidence": 1.0},
    {"fact_id": "phys_028", "category": "physical", "fact": "A parachute slows falling by increasing air resistance", "confidence": 1.0},
    {"fact_id": "phys_029", "category": "physical", "fact": "Feathers fall slowly because of air resistance", "confidence": 1.0},
    {"fact_id": "phys_030", "category": "physical", "fact": "Centrifugal force pushes objects outward in circular motion", "confidence": 0.9},
    {"fact_id": "phys_031", "category": "physical", "fact": "Tightrope walkers use balance to counteract gravity", "confidence": 1.0},
    {"fact_id": "phys_032", "category": "physical", "fact": "A lever can multiply force", "confidence": 1.0},
    {"fact_id": "phys_033", "category": "physical", "fact": "Pulleys change the direction of force", "confidence": 1.0},
    {"fact_id": "phys_034", "category": "physical", "fact": "An inclined plane reduces force needed to lift objects", "confidence": 1.0},
    {"fact_id": "phys_035", "category": "physical", "fact": "A wheel and axle reduce friction for movement", "confidence": 1.0},

    # ── Object Permanence ──
    {"fact_id": "phys_101", "category": "physical", "fact": "Objects continue to exist when not visible", "confidence": 1.0},
    {"fact_id": "phys_102", "category": "physical", "fact": "Objects don't disappear when you close your eyes", "confidence": 1.0},
    {"fact_id": "phys_103", "category": "physical", "fact": "Objects don't disappear when hidden behind other objects", "confidence": 1.0},
    {"fact_id": "phys_104", "category": "physical", "fact": "Objects don't disappear when you leave the room", "confidence": 1.0},
    {"fact_id": "phys_105", "category": "physical", "fact": "Objects don't disappear when put in a container", "confidence": 1.0},
    {"fact_id": "phys_106", "category": "physical", "fact": "Objects don't disappear when covered", "confidence": 1.0},
    {"fact_id": "phys_107", "category": "physical", "fact": "Objects don't disappear when put in a drawer", "confidence": 1.0},
    {"fact_id": "phys_108", "category": "physical", "fact": "Objects don't disappear when put in a box", "confidence": 1.0},
    {"fact_id": "phys_109", "category": "physical", "fact": "Objects don't disappear when put in a bag", "confidence": 1.0},
    {"fact_id": "phys_110", "category": "physical", "fact": "Objects don't disappear when put in a pocket", "confidence": 1.0},
    {"fact_id": "phys_111", "category": "physical", "fact": "Objects stay where you put them unless moved", "confidence": 1.0},
    {"fact_id": "phys_112", "category": "physical", "fact": "Objects behind a wall are still there", "confidence": 1.0},
    {"fact_id": "phys_113", "category": "physical", "fact": "Furniture stays in a room when lights are off", "confidence": 1.0},
    {"fact_id": "phys_114", "category": "physical", "fact": "Food in a fridge continues to exist", "confidence": 1.0},
    {"fact_id": "phys_115", "category": "physical", "fact": "A car in a garage is still there when the door is closed", "confidence": 1.0},
    {"fact_id": "phys_116", "category": "physical", "fact": "Objects inside a closed box remain inside", "confidence": 1.0},
    {"fact_id": "phys_117", "category": "physical", "fact": "A person in another room still exists", "confidence": 1.0},
    {"fact_id": "phys_118", "category": "physical", "fact": "Buildings exist even when you cannot see them", "confidence": 1.0},
    {"fact_id": "phys_119", "category": "physical", "fact": "The sun exists when it is nighttime", "confidence": 1.0},
    {"fact_id": "phys_120", "category": "physical", "fact": "Stars exist during the day even though you cannot see them", "confidence": 1.0},

    # ── Material Properties ──
    {"fact_id": "phys_201", "category": "physical", "fact": "Glass is transparent", "confidence": 1.0},
    {"fact_id": "phys_202", "category": "physical", "fact": "Glass is brittle", "confidence": 1.0},
    {"fact_id": "phys_203", "category": "physical", "fact": "Glass breaks when dropped", "confidence": 1.0},
    {"fact_id": "phys_204", "category": "physical", "fact": "Glass shatters into sharp pieces", "confidence": 1.0},
    {"fact_id": "phys_205", "category": "physical", "fact": "Metal is hard", "confidence": 1.0},
    {"fact_id": "phys_206", "category": "physical", "fact": "Metal is strong", "confidence": 1.0},
    {"fact_id": "phys_207", "category": "physical", "fact": "Metal conducts heat", "confidence": 1.0},
    {"fact_id": "phys_208", "category": "physical", "fact": "Metal conducts electricity", "confidence": 1.0},
    {"fact_id": "phys_209", "category": "physical", "fact": "Wood is solid", "confidence": 1.0},
    {"fact_id": "phys_210", "category": "physical", "fact": "Wood burns", "confidence": 1.0},
    {"fact_id": "phys_211", "category": "physical", "fact": "Wood floats in water", "confidence": 1.0},
    {"fact_id": "phys_212", "category": "physical", "fact": "Wood is combustible", "confidence": 1.0},
    {"fact_id": "phys_213", "category": "physical", "fact": "Plastic is lightweight", "confidence": 1.0},
    {"fact_id": "phys_214", "category": "physical", "fact": "Plastic is flexible", "confidence": 1.0},
    {"fact_id": "phys_215", "category": "physical", "fact": "Plastic melts when heated", "confidence": 1.0},
    {"fact_id": "phys_216", "category": "physical", "fact": "Rubber is flexible", "confidence": 1.0},
    {"fact_id": "phys_217", "category": "physical", "fact": "Rubber is elastic", "confidence": 1.0},
    {"fact_id": "phys_218", "category": "physical", "fact": "Rubber is waterproof", "confidence": 1.0},
    {"fact_id": "phys_219", "category": "physical", "fact": "Paper is thin", "confidence": 1.0},
    {"fact_id": "phys_220", "category": "physical", "fact": "Paper tears easily", "confidence": 1.0},
    {"fact_id": "phys_221", "category": "physical", "fact": "Paper burns easily", "confidence": 1.0},
    {"fact_id": "phys_222", "category": "physical", "fact": "Paper absorbs water", "confidence": 1.0},
    {"fact_id": "phys_223", "category": "physical", "fact": "Fabric can absorb liquids", "confidence": 1.0},
    {"fact_id": "phys_224", "category": "physical", "fact": "Cotton is soft and breathable", "confidence": 1.0},
    {"fact_id": "phys_225", "category": "physical", "fact": "Leather is durable and water-resistant", "confidence": 1.0},
    {"fact_id": "phys_226", "category": "physical", "fact": "Ceramic is hard but brittle", "confidence": 1.0},
    {"fact_id": "phys_227", "category": "physical", "fact": "Concrete is strong under compression", "confidence": 1.0},
    {"fact_id": "phys_228", "category": "physical", "fact": "Steel is an alloy of iron and carbon", "confidence": 1.0},
    {"fact_id": "phys_229", "category": "physical", "fact": "Aluminum is lightweight and corrosion-resistant", "confidence": 1.0},
    {"fact_id": "phys_230", "category": "physical", "fact": "Copper conducts electricity well", "confidence": 1.0},
    {"fact_id": "phys_231", "category": "physical", "fact": "Gold does not rust or tarnish", "confidence": 1.0},
    {"fact_id": "phys_232", "category": "physical", "fact": "Iron rusts when exposed to water and oxygen", "confidence": 1.0},
    {"fact_id": "phys_233", "category": "physical", "fact": "Diamond is the hardest natural material", "confidence": 1.0},
    {"fact_id": "phys_234", "category": "physical", "fact": "Sponge is soft and absorbs water", "confidence": 1.0},
    {"fact_id": "phys_235", "category": "physical", "fact": "Sand is granular and flows like a liquid", "confidence": 0.9},

    # ── Physical Laws / Energy ──
    {"fact_id": "phys_301", "category": "physical", "fact": "Energy cannot be created or destroyed", "confidence": 1.0},
    {"fact_id": "phys_302", "category": "physical", "fact": "Energy can be transformed from one form to another", "confidence": 1.0},
    {"fact_id": "phys_303", "category": "physical", "fact": "Kinetic energy is energy of motion", "confidence": 1.0},
    {"fact_id": "phys_304", "category": "physical", "fact": "Potential energy is stored energy", "confidence": 1.0},
    {"fact_id": "phys_305", "category": "physical", "fact": "Heat is a form of energy", "confidence": 1.0},
    {"fact_id": "phys_306", "category": "physical", "fact": "Light is a form of energy", "confidence": 1.0},
    {"fact_id": "phys_307", "category": "physical", "fact": "Sound is a form of energy", "confidence": 1.0},
    {"fact_id": "phys_308", "category": "physical", "fact": "Electricity is a form of energy", "confidence": 1.0},
    {"fact_id": "phys_309", "category": "physical", "fact": "Chemical energy is stored in chemical bonds", "confidence": 1.0},
    {"fact_id": "phys_310", "category": "physical", "fact": "Nuclear energy is stored in atomic nuclei", "confidence": 1.0},
    {"fact_id": "phys_311", "category": "physical", "fact": "Force equals mass times acceleration", "confidence": 1.0},
    {"fact_id": "phys_312", "category": "physical", "fact": "Every action has an equal and opposite reaction", "confidence": 1.0},
    {"fact_id": "phys_313", "category": "physical", "fact": "Momentum is conserved in collisions", "confidence": 1.0},
    {"fact_id": "phys_314", "category": "physical", "fact": "Angular momentum is conserved", "confidence": 1.0},
    {"fact_id": "phys_315", "category": "physical", "fact": "Pressure is force per unit area", "confidence": 1.0},
    {"fact_id": "phys_316", "category": "physical", "fact": "Buoyancy equals weight of displaced fluid", "confidence": 1.0},
    {"fact_id": "phys_317", "category": "physical", "fact": "Viscosity is resistance to flow", "confidence": 1.0},
    {"fact_id": "phys_318", "category": "physical", "fact": "Surface tension makes water form droplets", "confidence": 1.0},
    {"fact_id": "phys_319", "category": "physical", "fact": "Capillary action makes water rise in thin tubes", "confidence": 1.0},
    {"fact_id": "phys_320", "category": "physical", "fact": "Diffusion makes particles spread from high to low concentration", "confidence": 1.0},
    {"fact_id": "phys_321", "category": "physical", "fact": "Heat flows from hot objects to cold objects", "confidence": 1.0},
    {"fact_id": "phys_322", "category": "physical", "fact": "Entropy in a closed system always increases", "confidence": 1.0},
    {"fact_id": "phys_323", "category": "physical", "fact": "Work is force applied over a distance", "confidence": 1.0},
    {"fact_id": "phys_324", "category": "physical", "fact": "Power is the rate of doing work", "confidence": 1.0},
    {"fact_id": "phys_325", "category": "physical", "fact": "Springs store potential energy when compressed or stretched", "confidence": 1.0},

    # ── Temperature and States of Matter ──
    {"fact_id": "phys_401", "category": "physical", "fact": "Water boils at 100 degrees Celsius at sea level", "confidence": 1.0},
    {"fact_id": "phys_402", "category": "physical", "fact": "Water freezes at 0 degrees Celsius", "confidence": 1.0},
    {"fact_id": "phys_403", "category": "physical", "fact": "Water expands when it freezes", "confidence": 1.0},
    {"fact_id": "phys_404", "category": "physical", "fact": "Ice is less dense than liquid water", "confidence": 1.0},
    {"fact_id": "phys_405", "category": "physical", "fact": "Steam is water in gas form", "confidence": 1.0},
    {"fact_id": "phys_406", "category": "physical", "fact": "Water evaporates when heated", "confidence": 1.0},
    {"fact_id": "phys_407", "category": "physical", "fact": "Water condenses when cooled", "confidence": 1.0},
    {"fact_id": "phys_408", "category": "physical", "fact": "Water is a good solvent", "confidence": 0.9},
    {"fact_id": "phys_409", "category": "physical", "fact": "Salt dissolves in water", "confidence": 1.0},
    {"fact_id": "phys_410", "category": "physical", "fact": "Sugar dissolves in water", "confidence": 1.0},
    {"fact_id": "phys_411", "category": "physical", "fact": "Oil does not mix with water", "confidence": 1.0},
    {"fact_id": "phys_412", "category": "physical", "fact": "Soap helps oil mix with water", "confidence": 1.0},
    {"fact_id": "phys_413", "category": "physical", "fact": "Hot water dissolves things faster than cold water", "confidence": 1.0},
    {"fact_id": "phys_414", "category": "physical", "fact": "Stirring helps things dissolve faster", "confidence": 1.0},
    {"fact_id": "phys_415", "category": "physical", "fact": "Crushing solids helps them dissolve faster", "confidence": 1.0},
    {"fact_id": "phys_416", "category": "physical", "fact": "Solids have a fixed shape", "confidence": 1.0},
    {"fact_id": "phys_417", "category": "physical", "fact": "Liquids take the shape of their container", "confidence": 1.0},
    {"fact_id": "phys_418", "category": "physical", "fact": "Gases fill their entire container", "confidence": 1.0},
    {"fact_id": "phys_419", "category": "physical", "fact": "Melting is the transition from solid to liquid", "confidence": 1.0},
    {"fact_id": "phys_420", "category": "physical", "fact": "Freezing is the transition from liquid to solid", "confidence": 1.0},
    {"fact_id": "phys_421", "category": "physical", "fact": "Evaporation is the transition from liquid to gas", "confidence": 1.0},
    {"fact_id": "phys_422", "category": "physical", "fact": "Condensation is the transition from gas to liquid", "confidence": 1.0},
    {"fact_id": "phys_423", "category": "physical", "fact": "Sublimation is the transition from solid directly to gas", "confidence": 1.0},
    {"fact_id": "phys_424", "category": "physical", "fact": "Metals melt at very high temperatures", "confidence": 1.0},
    {"fact_id": "phys_425", "category": "physical", "fact": "Ice cream melts at room temperature", "confidence": 1.0},
    {"fact_id": "phys_426", "category": "physical", "fact": "Chocolate melts in your hand", "confidence": 1.0},
    {"fact_id": "phys_427", "category": "physical", "fact": "Butter melts when heated", "confidence": 1.0},
    {"fact_id": "phys_428", "category": "physical", "fact": "Wax melts when heated", "confidence": 1.0},
    {"fact_id": "phys_429", "category": "physical", "fact": "Dry ice sublimates at room temperature", "confidence": 1.0},
    {"fact_id": "phys_430", "category": "physical", "fact": "Nitrogen is a gas at room temperature", "confidence": 1.0},

    # ── Light and Optics ──
    {"fact_id": "phys_501", "category": "physical", "fact": "Light travels in straight lines", "confidence": 1.0},
    {"fact_id": "phys_502", "category": "physical", "fact": "Light travels faster than sound", "confidence": 1.0},
    {"fact_id": "phys_503", "category": "physical", "fact": "Shadows are formed when light is blocked", "confidence": 1.0},
    {"fact_id": "phys_504", "category": "physical", "fact": "Mirrors reflect light", "confidence": 1.0},
    {"fact_id": "phys_505", "category": "physical", "fact": "Lenses bend light", "confidence": 1.0},
    {"fact_id": "phys_506", "category": "physical", "fact": "White light is made of all colors", "confidence": 1.0},
    {"fact_id": "phys_507", "category": "physical", "fact": "A prism splits white light into a rainbow", "confidence": 1.0},
    {"fact_id": "phys_508", "category": "physical", "fact": "Red objects reflect red light and absorb other colors", "confidence": 1.0},
    {"fact_id": "phys_509", "category": "physical", "fact": "Black objects absorb most visible light", "confidence": 1.0},
    {"fact_id": "phys_510", "category": "physical", "fact": "White objects reflect most visible light", "confidence": 1.0},
    {"fact_id": "phys_511", "category": "physical", "fact": "Transparent objects let light pass through", "confidence": 1.0},
    {"fact_id": "phys_512", "category": "physical", "fact": "Opaque objects block light", "confidence": 1.0},
    {"fact_id": "phys_513", "category": "physical", "fact": "Translucent objects let some light through but scatter it", "confidence": 1.0},
    {"fact_id": "phys_514", "category": "physical", "fact": "You see lightning before you hear thunder because light is faster than sound", "confidence": 1.0},
    {"fact_id": "phys_515", "category": "physical", "fact": "A rainbow appears when sunlight passes through raindrops", "confidence": 1.0},
    {"fact_id": "phys_516", "category": "physical", "fact": "Dark colors absorb more heat than light colors", "confidence": 1.0},
    {"fact_id": "phys_517", "category": "physical", "fact": "Magnifying glasses make objects look bigger", "confidence": 1.0},
    {"fact_id": "phys_518", "category": "physical", "fact": "Sunglasses reduce the amount of light reaching your eyes", "confidence": 1.0},
    {"fact_id": "phys_519", "category": "physical", "fact": "Glasses correct vision by bending light", "confidence": 1.0},
    {"fact_id": "phys_520", "category": "physical", "fact": "Telescopes use lenses or mirrors to see distant objects", "confidence": 1.0},

    # ── Electricity and Magnetism ──
    {"fact_id": "phys_601", "category": "physical", "fact": "Electricity flows through conductors", "confidence": 1.0},
    {"fact_id": "phys_602", "category": "physical", "fact": "Electricity does not flow through insulators", "confidence": 1.0},
    {"fact_id": "phys_603", "category": "physical", "fact": "Metal is a good conductor of electricity", "confidence": 1.0},
    {"fact_id": "phys_604", "category": "physical", "fact": "Rubber is a good insulator", "confidence": 1.0},
    {"fact_id": "phys_605", "category": "physical", "fact": "Water conducts electricity", "confidence": 0.9},
    {"fact_id": "phys_606", "category": "physical", "fact": "Batteries store chemical energy and convert it to electrical energy", "confidence": 1.0},
    {"fact_id": "phys_607", "category": "physical", "fact": "A complete circuit is needed for electricity to flow", "confidence": 1.0},
    {"fact_id": "phys_608", "category": "physical", "fact": "A switch opens or closes a circuit", "confidence": 1.0},
    {"fact_id": "phys_609", "category": "physical", "fact": "Fuses protect circuits from too much current", "confidence": 1.0},
    {"fact_id": "phys_610", "category": "physical", "fact": "Magnets attract iron and steel", "confidence": 1.0},
    {"fact_id": "phys_611", "category": "physical", "fact": "Magnets have a north and south pole", "confidence": 1.0},
    {"fact_id": "phys_612", "category": "physical", "fact": "Like poles of magnets repel each other", "confidence": 1.0},
    {"fact_id": "phys_613", "category": "physical", "fact": "Opposite poles of magnets attract each other", "confidence": 1.0},
    {"fact_id": "phys_614", "category": "physical", "fact": "Electromagnets work only when electricity flows through them", "confidence": 1.0},
    {"fact_id": "phys_615", "category": "physical", "fact": "The Earth has a magnetic field", "confidence": 1.0},
    {"fact_id": "phys_616", "category": "physical", "fact": "A compass needle points north because of Earth's magnetic field", "confidence": 1.0},
    {"fact_id": "phys_617", "category": "physical", "fact": "Static electricity builds up from friction", "confidence": 1.0},
    {"fact_id": "phys_618", "category": "physical", "fact": "Lightning is a large discharge of static electricity", "confidence": 1.0},
    {"fact_id": "phys_619", "category": "physical", "fact": "Generators convert mechanical energy to electrical energy", "confidence": 1.0},
    {"fact_id": "phys_620", "category": "physical", "fact": "Motors convert electrical energy to mechanical energy", "confidence": 1.0},
]
