"""
Technology and Computing Knowledge

Facts about technology including:
- Computers and hardware
- Software and programming
- Networks and internet
- Data and storage
- Security and privacy
"""

TECHNOLOGY_KNOWLEDGE_FACTS = [
    # ── Computers and Hardware ──
    {"fact_id": "tech_001", "category": "technology", "fact": "A computer has a CPU that processes instructions", "confidence": 1.0},
    {"fact_id": "tech_002", "category": "technology", "fact": "RAM is volatile memory that loses data when powered off", "confidence": 1.0},
    {"fact_id": "tech_003", "category": "technology", "fact": "A hard drive stores data permanently", "confidence": 1.0},
    {"fact_id": "tech_004", "category": "technology", "fact": "SSDs are faster than traditional hard drives", "confidence": 1.0},
    {"fact_id": "tech_005", "category": "technology", "fact": "A GPU handles graphics processing", "confidence": 1.0},
    {"fact_id": "tech_006", "category": "technology", "fact": "More RAM allows more programs to run simultaneously", "confidence": 1.0},
    {"fact_id": "tech_007", "category": "technology", "fact": "A motherboard connects all computer components", "confidence": 1.0},
    {"fact_id": "tech_008", "category": "technology", "fact": "USB ports connect external devices", "confidence": 1.0},
    {"fact_id": "tech_009", "category": "technology", "fact": "A power supply converts AC to DC power", "confidence": 1.0},
    {"fact_id": "tech_010", "category": "technology", "fact": "Computers generate heat and need cooling", "confidence": 1.0},
    {"fact_id": "tech_011", "category": "technology", "fact": "A monitor displays visual output", "confidence": 1.0},
    {"fact_id": "tech_012", "category": "technology", "fact": "A keyboard is used for text input", "confidence": 1.0},
    {"fact_id": "tech_013", "category": "technology", "fact": "A mouse controls the cursor on screen", "confidence": 1.0},
    {"fact_id": "tech_014", "category": "technology", "fact": "Laptops have built-in batteries for portability", "confidence": 1.0},
    {"fact_id": "tech_015", "category": "technology", "fact": "Smartphones are pocket-sized computers", "confidence": 1.0},
    {"fact_id": "tech_016", "category": "technology", "fact": "Processors are measured in GHz (gigahertz)", "confidence": 1.0},
    {"fact_id": "tech_017", "category": "technology", "fact": "Multi-core processors can handle multiple tasks in parallel", "confidence": 1.0},
    {"fact_id": "tech_018", "category": "technology", "fact": "Overheating can damage computer components", "confidence": 1.0},
    {"fact_id": "tech_019", "category": "technology", "fact": "Dust buildup reduces cooling efficiency", "confidence": 1.0},
    {"fact_id": "tech_020", "category": "technology", "fact": "A UPS provides backup power during outages", "confidence": 1.0},
    
    # ── Software and Programming ──
    {"fact_id": "tech_101", "category": "technology", "fact": "An operating system manages hardware and software resources", "confidence": 1.0},
    {"fact_id": "tech_102", "category": "technology", "fact": "Windows, macOS, and Linux are operating systems", "confidence": 1.0},
    {"fact_id": "tech_103", "category": "technology", "fact": "Applications are programs that perform specific tasks", "confidence": 1.0},
    {"fact_id": "tech_104", "category": "technology", "fact": "A web browser displays web pages", "confidence": 1.0},
    {"fact_id": "tech_105", "category": "technology", "fact": "Software updates fix bugs and add features", "confidence": 1.0},
    {"fact_id": "tech_106", "category": "technology", "fact": "Python is a programming language", "confidence": 1.0},
    {"fact_id": "tech_107", "category": "technology", "fact": "Code is written in programming languages", "confidence": 1.0},
    {"fact_id": "tech_108", "category": "technology", "fact": "Compilers translate code into machine instructions", "confidence": 1.0},
    {"fact_id": "tech_109", "category": "technology", "fact": "Bugs are errors in software code", "confidence": 1.0},
    {"fact_id": "tech_110", "category": "technology", "fact": "Debugging is the process of finding and fixing bugs", "confidence": 1.0},
    {"fact_id": "tech_111", "category": "technology", "fact": "Open source software has publicly available source code", "confidence": 1.0},
    {"fact_id": "tech_112", "category": "technology", "fact": "Version control tracks changes to code", "confidence": 1.0},
    {"fact_id": "tech_113", "category": "technology", "fact": "Git is a version control system", "confidence": 1.0},
    {"fact_id": "tech_114", "category": "technology", "fact": "APIs allow different software to communicate", "confidence": 1.0},
    {"fact_id": "tech_115", "category": "technology", "fact": "Databases store structured data", "confidence": 1.0},
    {"fact_id": "tech_116", "category": "technology", "fact": "SQL is used to query databases", "confidence": 1.0},
    {"fact_id": "tech_117", "category": "technology", "fact": "A server provides services to other computers", "confidence": 1.0},
    {"fact_id": "tech_118", "category": "technology", "fact": "Cloud computing runs software on remote servers", "confidence": 1.0},
    {"fact_id": "tech_119", "category": "technology", "fact": "Virtual machines simulate computer environments", "confidence": 1.0},
    {"fact_id": "tech_120", "category": "technology", "fact": "Containers package applications with their dependencies", "confidence": 1.0},
    
    # ── Networks and Internet ──
    {"fact_id": "tech_201", "category": "technology", "fact": "The internet is a global network of networks", "confidence": 1.0},
    {"fact_id": "tech_202", "category": "technology", "fact": "IP addresses identify devices on a network", "confidence": 1.0},
    {"fact_id": "tech_203", "category": "technology", "fact": "DNS translates domain names to IP addresses", "confidence": 1.0},
    {"fact_id": "tech_204", "category": "technology", "fact": "HTTP is the protocol for web communication", "confidence": 1.0},
    {"fact_id": "tech_205", "category": "technology", "fact": "HTTPS encrypts web traffic", "confidence": 1.0},
    {"fact_id": "tech_206", "category": "technology", "fact": "A router directs network traffic", "confidence": 1.0},
    {"fact_id": "tech_207", "category": "technology", "fact": "WiFi provides wireless internet access", "confidence": 1.0},
    {"fact_id": "tech_208", "category": "technology", "fact": "Ethernet cables provide wired network connections", "confidence": 1.0},
    {"fact_id": "tech_209", "category": "technology", "fact": "Bandwidth is the maximum data transfer rate", "confidence": 1.0},
    {"fact_id": "tech_210", "category": "technology", "fact": "Latency is the delay in data transmission", "confidence": 1.0},
    {"fact_id": "tech_211", "category": "technology", "fact": "Packets are units of data sent over networks", "confidence": 1.0},
    {"fact_id": "tech_212", "category": "technology", "fact": "A firewall filters network traffic", "confidence": 1.0},
    {"fact_id": "tech_213", "category": "technology", "fact": "Email sends messages over the internet", "confidence": 1.0},
    {"fact_id": "tech_214", "category": "technology", "fact": "SMTP is the protocol for sending email", "confidence": 1.0},
    {"fact_id": "tech_215", "category": "technology", "fact": "A URL is a web address", "confidence": 1.0},
    {"fact_id": "tech_216", "category": "technology", "fact": "Websites are hosted on servers", "confidence": 1.0},
    {"fact_id": "tech_217", "category": "technology", "fact": "HTML structures web page content", "confidence": 1.0},
    {"fact_id": "tech_218", "category": "technology", "fact": "CSS styles web page appearance", "confidence": 1.0},
    {"fact_id": "tech_219", "category": "technology", "fact": "JavaScript adds interactivity to web pages", "confidence": 1.0},
    {"fact_id": "tech_220", "category": "technology", "fact": "Cookies store small amounts of data in browsers", "confidence": 1.0},
    
    # ── Data and Storage ──
    {"fact_id": "tech_301", "category": "technology", "fact": "A byte is 8 bits", "confidence": 1.0},
    {"fact_id": "tech_302", "category": "technology", "fact": "A kilobyte is 1024 bytes", "confidence": 1.0},
    {"fact_id": "tech_303", "category": "technology", "fact": "A megabyte is 1024 kilobytes", "confidence": 1.0},
    {"fact_id": "tech_304", "category": "technology", "fact": "A gigabyte is 1024 megabytes", "confidence": 1.0},
    {"fact_id": "tech_305", "category": "technology", "fact": "A terabyte is 1024 gigabytes", "confidence": 1.0},
    {"fact_id": "tech_306", "category": "technology", "fact": "Files are stored in directories or folders", "confidence": 1.0},
    {"fact_id": "tech_307", "category": "technology", "fact": "File extensions indicate file types", "confidence": 1.0},
    {"fact_id": "tech_308", "category": "technology", "fact": "Text files contain readable characters", "confidence": 1.0},
    {"fact_id": "tech_309", "category": "technology", "fact": "Binary files contain non-text data", "confidence": 1.0},
    {"fact_id": "tech_310", "category": "technology", "fact": "Compression reduces file size", "confidence": 1.0},
    {"fact_id": "tech_311", "category": "technology", "fact": "ZIP files are compressed archives", "confidence": 1.0},
    {"fact_id": "tech_312", "category": "technology", "fact": "Backups protect against data loss", "confidence": 1.0},
    {"fact_id": "tech_313", "category": "technology", "fact": "Cloud storage keeps data on remote servers", "confidence": 1.0},
    {"fact_id": "tech_314", "category": "technology", "fact": "Encryption scrambles data to protect it", "confidence": 1.0},
    {"fact_id": "tech_315", "category": "technology", "fact": "Decryption reverses encryption", "confidence": 1.0},
    {"fact_id": "tech_316", "category": "technology", "fact": "JSON is a data format using key-value pairs", "confidence": 1.0},
    {"fact_id": "tech_317", "category": "technology", "fact": "XML uses tags to structure data", "confidence": 1.0},
    {"fact_id": "tech_318", "category": "technology", "fact": "CSV stores tabular data as comma-separated values", "confidence": 1.0},
    {"fact_id": "tech_319", "category": "technology", "fact": "Deleting a file doesn't immediately erase it from disk", "confidence": 1.0},
    {"fact_id": "tech_320", "category": "technology", "fact": "Formatting a drive prepares it for data storage", "confidence": 1.0},
    
    # ── Security and Privacy ──
    {"fact_id": "tech_401", "category": "technology", "fact": "Passwords protect accounts", "confidence": 1.0},
    {"fact_id": "tech_402", "category": "technology", "fact": "Strong passwords are long and complex", "confidence": 1.0},
    {"fact_id": "tech_403", "category": "technology", "fact": "Two-factor authentication adds an extra security layer", "confidence": 1.0},
    {"fact_id": "tech_404", "category": "technology", "fact": "Malware is malicious software", "confidence": 1.0},
    {"fact_id": "tech_405", "category": "technology", "fact": "Viruses are malware that replicate", "confidence": 1.0},
    {"fact_id": "tech_406", "category": "technology", "fact": "Antivirus software detects and removes malware", "confidence": 1.0},
    {"fact_id": "tech_407", "category": "technology", "fact": "Phishing uses fake emails to steal information", "confidence": 1.0},
    {"fact_id": "tech_408", "category": "technology", "fact": "Encryption protects data in transit", "confidence": 1.0},
    {"fact_id": "tech_409", "category": "technology", "fact": "VPNs encrypt internet traffic", "confidence": 1.0},
    {"fact_id": "tech_410", "category": "technology", "fact": "Permissions control what software can access", "confidence": 1.0},
    {"fact_id": "tech_411", "category": "technology", "fact": "Admin accounts have elevated privileges", "confidence": 1.0},
    {"fact_id": "tech_412", "category": "technology", "fact": "Patches fix security vulnerabilities", "confidence": 1.0},
    {"fact_id": "tech_413", "category": "technology", "fact": "Zero-day exploits target unknown vulnerabilities", "confidence": 1.0},
    {"fact_id": "tech_414", "category": "technology", "fact": "Social engineering manipulates people into revealing information", "confidence": 1.0},
    {"fact_id": "tech_415", "category": "technology", "fact": "Cookies can track user behavior", "confidence": 1.0},
    {"fact_id": "tech_416", "category": "technology", "fact": "Incognito mode doesn't store browsing history locally", "confidence": 1.0},
    {"fact_id": "tech_417", "category": "technology", "fact": "Public WiFi networks can be insecure", "confidence": 0.9},
    {"fact_id": "tech_418", "category": "technology", "fact": "Ransomware encrypts files and demands payment", "confidence": 1.0},
    {"fact_id": "tech_419", "category": "technology", "fact": "Security logs record system events", "confidence": 1.0},
    {"fact_id": "tech_420", "category": "technology", "fact": "Biometric authentication uses physical characteristics", "confidence": 1.0},
    
    # ── AI and Machine Learning ──
    {"fact_id": "tech_501", "category": "technology", "fact": "Artificial intelligence simulates human intelligence", "confidence": 1.0},
    {"fact_id": "tech_502", "category": "technology", "fact": "Machine learning learns patterns from data", "confidence": 1.0},
    {"fact_id": "tech_503", "category": "technology", "fact": "Neural networks are inspired by the brain", "confidence": 1.0},
    {"fact_id": "tech_504", "category": "technology", "fact": "Deep learning uses multiple neural network layers", "confidence": 1.0},
    {"fact_id": "tech_505", "category": "technology", "fact": "Training data teaches ML models", "confidence": 1.0},
    {"fact_id": "tech_506", "category": "technology", "fact": "Overfitting happens when models memorize training data", "confidence": 1.0},
    {"fact_id": "tech_507", "category": "technology", "fact": "GPUs accelerate neural network training", "confidence": 1.0},
    {"fact_id": "tech_508", "category": "technology", "fact": "Natural language processing handles human language", "confidence": 1.0},
    {"fact_id": "tech_509", "category": "technology", "fact": "Computer vision processes visual information", "confidence": 1.0},
    {"fact_id": "tech_510", "category": "technology", "fact": "Chatbots converse with users", "confidence": 1.0},
    {"fact_id": "tech_511", "category": "technology", "fact": "Reinforcement learning learns from rewards", "confidence": 1.0},
    {"fact_id": "tech_512", "category": "technology", "fact": "Supervised learning uses labeled data", "confidence": 1.0},
    {"fact_id": "tech_513", "category": "technology", "fact": "Unsupervised learning finds patterns without labels", "confidence": 1.0},
    {"fact_id": "tech_514", "category": "technology", "fact": "Large language models generate text", "confidence": 1.0},
    {"fact_id": "tech_515", "category": "technology", "fact": "AI models can have biases from training data", "confidence": 1.0},
]
